# fail-fast: true
# retry:
#    max-attempts: 6
#    initial-interval: 1000
#    max-interval: 2000
#    multiplier: 1.1
polar:
  greeting: Welcome to polar book service from local configuration file.
server:
  port: 9001
spring:
  application:
    name: polar-catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
  datasource:
    username: developer
    password: developer
    url: "jdbc:postgresql://localhost:5432/polardb_catalog"
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
management:
  endpoints:
    web:
      exposure:
        include: refresh
